package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG.
 */
public class Config {

    private Long id;
    private String conf_val;
    private String conf_note;
    private String conf_name;

    public Config() {
    }

    public Config(Long id) {
        this.id = id;
    }

    public Config(Long id, String conf_val, String conf_note, String conf_name) {
        this.id = id;
        this.conf_val = conf_val;
        this.conf_note = conf_note;
        this.conf_name = conf_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getConf_val() {
        return conf_val;
    }

    public void setConf_val(String conf_val) {
        this.conf_val = conf_val;
    }

    public String getConf_note() {
        return conf_note;
    }

    public void setConf_note(String conf_note) {
        this.conf_note = conf_note;
    }

    public String getConf_name() {
        return conf_name;
    }

    public void setConf_name(String conf_name) {
        this.conf_name = conf_name;
    }

}
