package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER_TYPE.
 */
public class CustomerType {

    private String ct_code;
    private Integer ct_pricelvl;
    private Float ct_discount;
    private Integer ct_point;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private String modi_date;

    public CustomerType() {
    }

    public CustomerType(String ct_code) {
        this.ct_code = ct_code;
    }

    public CustomerType(String ct_code, Integer ct_pricelvl, Float ct_discount, Integer ct_point, String src_code, Integer mark, String modi_by, String modi_date) {
        this.ct_code = ct_code;
        this.ct_pricelvl = ct_pricelvl;
        this.ct_discount = ct_discount;
        this.ct_point = ct_point;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getCt_code() {
        return ct_code;
    }

    public void setCt_code(String ct_code) {
        this.ct_code = ct_code;
    }

    public Integer getCt_pricelvl() {
        return ct_pricelvl;
    }

    public void setCt_pricelvl(Integer ct_pricelvl) {
        this.ct_pricelvl = ct_pricelvl;
    }

    public Float getCt_discount() {
        return ct_discount;
    }

    public void setCt_discount(Float ct_discount) {
        this.ct_discount = ct_discount;
    }

    public Integer getCt_point() {
        return ct_point;
    }

    public void setCt_point(Integer ct_point) {
        this.ct_point = ct_point;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public String getModi_date() {
        return modi_date;
    }

    public void setModi_date(String modi_date) {
        this.modi_date = modi_date;
    }

}
