package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER_INFO.
 */
public class CustomerInfo {

    private String ci_id;
    private String cust_code;
    private String ci_ctcperson;
    private String src_code;
    private String ori_code;

    public CustomerInfo() {
    }

    public CustomerInfo(String ci_id) {
        this.ci_id = ci_id;
    }

    public CustomerInfo(String ci_id, String cust_code, String ci_ctcperson, String src_code, String ori_code) {
        this.ci_id = ci_id;
        this.cust_code = cust_code;
        this.ci_ctcperson = ci_ctcperson;
        this.src_code = src_code;
        this.ori_code = ori_code;
    }

    public String getCi_id() {
        return ci_id;
    }

    public void setCi_id(String ci_id) {
        this.ci_id = ci_id;
    }

    public String getCust_code() {
        return cust_code;
    }

    public void setCust_code(String cust_code) {
        this.cust_code = cust_code;
    }

    public String getCi_ctcperson() {
        return ci_ctcperson;
    }

    public void setCi_ctcperson(String ci_ctcperson) {
        this.ci_ctcperson = ci_ctcperson;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public String getOri_code() {
        return ori_code;
    }

    public void setOri_code(String ori_code) {
        this.ori_code = ori_code;
    }

}
