package net.pointbridge.android.sales.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.pointbridge.android.sales.db.Inbox;
import net.pointbridge.android.sales.db.Config;
import net.pointbridge.android.sales.db.Warehouse;
import net.pointbridge.android.sales.db.Salesman;
import net.pointbridge.android.sales.db.Item;
import net.pointbridge.android.sales.db.ItemSerial;
import net.pointbridge.android.sales.db.ItemUnit;
import net.pointbridge.android.sales.db.ItemBarcode;
import net.pointbridge.android.sales.db.ItemPrice;
import net.pointbridge.android.sales.db.CustomerType;
import net.pointbridge.android.sales.db.Customer;
import net.pointbridge.android.sales.db.CustomerInfo;
import net.pointbridge.android.sales.db.TransferMaster;
import net.pointbridge.android.sales.db.TransferDetail;
import net.pointbridge.android.sales.db.TransferSerial;
import net.pointbridge.android.sales.db.MoveMaster;
import net.pointbridge.android.sales.db.MoveDetail;
import net.pointbridge.android.sales.db.MoveSerial;
import net.pointbridge.android.sales.db.SalesMaster;
import net.pointbridge.android.sales.db.SalesDetail;
import net.pointbridge.android.sales.db.SalesSerial;
import net.pointbridge.android.sales.db.SoMaster;
import net.pointbridge.android.sales.db.SoDetail;
import net.pointbridge.android.sales.db.SrMaster;
import net.pointbridge.android.sales.db.SrDetail;
import net.pointbridge.android.sales.db.SrSerial;

import net.pointbridge.android.sales.db.InboxDao;
import net.pointbridge.android.sales.db.ConfigDao;
import net.pointbridge.android.sales.db.WarehouseDao;
import net.pointbridge.android.sales.db.SalesmanDao;
import net.pointbridge.android.sales.db.ItemDao;
import net.pointbridge.android.sales.db.ItemSerialDao;
import net.pointbridge.android.sales.db.ItemUnitDao;
import net.pointbridge.android.sales.db.ItemBarcodeDao;
import net.pointbridge.android.sales.db.ItemPriceDao;
import net.pointbridge.android.sales.db.CustomerTypeDao;
import net.pointbridge.android.sales.db.CustomerDao;
import net.pointbridge.android.sales.db.CustomerInfoDao;
import net.pointbridge.android.sales.db.TransferMasterDao;
import net.pointbridge.android.sales.db.TransferDetailDao;
import net.pointbridge.android.sales.db.TransferSerialDao;
import net.pointbridge.android.sales.db.MoveMasterDao;
import net.pointbridge.android.sales.db.MoveDetailDao;
import net.pointbridge.android.sales.db.MoveSerialDao;
import net.pointbridge.android.sales.db.SalesMasterDao;
import net.pointbridge.android.sales.db.SalesDetailDao;
import net.pointbridge.android.sales.db.SalesSerialDao;
import net.pointbridge.android.sales.db.SoMasterDao;
import net.pointbridge.android.sales.db.SoDetailDao;
import net.pointbridge.android.sales.db.SrMasterDao;
import net.pointbridge.android.sales.db.SrDetailDao;
import net.pointbridge.android.sales.db.SrSerialDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inboxDaoConfig;
    private final DaoConfig configDaoConfig;
    private final DaoConfig warehouseDaoConfig;
    private final DaoConfig salesmanDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig itemSerialDaoConfig;
    private final DaoConfig itemUnitDaoConfig;
    private final DaoConfig itemBarcodeDaoConfig;
    private final DaoConfig itemPriceDaoConfig;
    private final DaoConfig customerTypeDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig customerInfoDaoConfig;
    private final DaoConfig transferMasterDaoConfig;
    private final DaoConfig transferDetailDaoConfig;
    private final DaoConfig transferSerialDaoConfig;
    private final DaoConfig moveMasterDaoConfig;
    private final DaoConfig moveDetailDaoConfig;
    private final DaoConfig moveSerialDaoConfig;
    private final DaoConfig salesMasterDaoConfig;
    private final DaoConfig salesDetailDaoConfig;
    private final DaoConfig salesSerialDaoConfig;
    private final DaoConfig soMasterDaoConfig;
    private final DaoConfig soDetailDaoConfig;
    private final DaoConfig srMasterDaoConfig;
    private final DaoConfig srDetailDaoConfig;
    private final DaoConfig srSerialDaoConfig;

    private final InboxDao inboxDao;
    private final ConfigDao configDao;
    private final WarehouseDao warehouseDao;
    private final SalesmanDao salesmanDao;
    private final ItemDao itemDao;
    private final ItemSerialDao itemSerialDao;
    private final ItemUnitDao itemUnitDao;
    private final ItemBarcodeDao itemBarcodeDao;
    private final ItemPriceDao itemPriceDao;
    private final CustomerTypeDao customerTypeDao;
    private final CustomerDao customerDao;
    private final CustomerInfoDao customerInfoDao;
    private final TransferMasterDao transferMasterDao;
    private final TransferDetailDao transferDetailDao;
    private final TransferSerialDao transferSerialDao;
    private final MoveMasterDao moveMasterDao;
    private final MoveDetailDao moveDetailDao;
    private final MoveSerialDao moveSerialDao;
    private final SalesMasterDao salesMasterDao;
    private final SalesDetailDao salesDetailDao;
    private final SalesSerialDao salesSerialDao;
    private final SoMasterDao soMasterDao;
    private final SoDetailDao soDetailDao;
    private final SrMasterDao srMasterDao;
    private final SrDetailDao srDetailDao;
    private final SrSerialDao srSerialDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inboxDaoConfig = daoConfigMap.get(InboxDao.class).clone();
        inboxDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        warehouseDaoConfig = daoConfigMap.get(WarehouseDao.class).clone();
        warehouseDaoConfig.initIdentityScope(type);

        salesmanDaoConfig = daoConfigMap.get(SalesmanDao.class).clone();
        salesmanDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        itemSerialDaoConfig = daoConfigMap.get(ItemSerialDao.class).clone();
        itemSerialDaoConfig.initIdentityScope(type);

        itemUnitDaoConfig = daoConfigMap.get(ItemUnitDao.class).clone();
        itemUnitDaoConfig.initIdentityScope(type);

        itemBarcodeDaoConfig = daoConfigMap.get(ItemBarcodeDao.class).clone();
        itemBarcodeDaoConfig.initIdentityScope(type);

        itemPriceDaoConfig = daoConfigMap.get(ItemPriceDao.class).clone();
        itemPriceDaoConfig.initIdentityScope(type);

        customerTypeDaoConfig = daoConfigMap.get(CustomerTypeDao.class).clone();
        customerTypeDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        customerInfoDaoConfig = daoConfigMap.get(CustomerInfoDao.class).clone();
        customerInfoDaoConfig.initIdentityScope(type);

        transferMasterDaoConfig = daoConfigMap.get(TransferMasterDao.class).clone();
        transferMasterDaoConfig.initIdentityScope(type);

        transferDetailDaoConfig = daoConfigMap.get(TransferDetailDao.class).clone();
        transferDetailDaoConfig.initIdentityScope(type);

        transferSerialDaoConfig = daoConfigMap.get(TransferSerialDao.class).clone();
        transferSerialDaoConfig.initIdentityScope(type);

        moveMasterDaoConfig = daoConfigMap.get(MoveMasterDao.class).clone();
        moveMasterDaoConfig.initIdentityScope(type);

        moveDetailDaoConfig = daoConfigMap.get(MoveDetailDao.class).clone();
        moveDetailDaoConfig.initIdentityScope(type);

        moveSerialDaoConfig = daoConfigMap.get(MoveSerialDao.class).clone();
        moveSerialDaoConfig.initIdentityScope(type);

        salesMasterDaoConfig = daoConfigMap.get(SalesMasterDao.class).clone();
        salesMasterDaoConfig.initIdentityScope(type);

        salesDetailDaoConfig = daoConfigMap.get(SalesDetailDao.class).clone();
        salesDetailDaoConfig.initIdentityScope(type);

        salesSerialDaoConfig = daoConfigMap.get(SalesSerialDao.class).clone();
        salesSerialDaoConfig.initIdentityScope(type);

        soMasterDaoConfig = daoConfigMap.get(SoMasterDao.class).clone();
        soMasterDaoConfig.initIdentityScope(type);

        soDetailDaoConfig = daoConfigMap.get(SoDetailDao.class).clone();
        soDetailDaoConfig.initIdentityScope(type);

        srMasterDaoConfig = daoConfigMap.get(SrMasterDao.class).clone();
        srMasterDaoConfig.initIdentityScope(type);

        srDetailDaoConfig = daoConfigMap.get(SrDetailDao.class).clone();
        srDetailDaoConfig.initIdentityScope(type);

        srSerialDaoConfig = daoConfigMap.get(SrSerialDao.class).clone();
        srSerialDaoConfig.initIdentityScope(type);

        inboxDao = new InboxDao(inboxDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);
        warehouseDao = new WarehouseDao(warehouseDaoConfig, this);
        salesmanDao = new SalesmanDao(salesmanDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        itemSerialDao = new ItemSerialDao(itemSerialDaoConfig, this);
        itemUnitDao = new ItemUnitDao(itemUnitDaoConfig, this);
        itemBarcodeDao = new ItemBarcodeDao(itemBarcodeDaoConfig, this);
        itemPriceDao = new ItemPriceDao(itemPriceDaoConfig, this);
        customerTypeDao = new CustomerTypeDao(customerTypeDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        customerInfoDao = new CustomerInfoDao(customerInfoDaoConfig, this);
        transferMasterDao = new TransferMasterDao(transferMasterDaoConfig, this);
        transferDetailDao = new TransferDetailDao(transferDetailDaoConfig, this);
        transferSerialDao = new TransferSerialDao(transferSerialDaoConfig, this);
        moveMasterDao = new MoveMasterDao(moveMasterDaoConfig, this);
        moveDetailDao = new MoveDetailDao(moveDetailDaoConfig, this);
        moveSerialDao = new MoveSerialDao(moveSerialDaoConfig, this);
        salesMasterDao = new SalesMasterDao(salesMasterDaoConfig, this);
        salesDetailDao = new SalesDetailDao(salesDetailDaoConfig, this);
        salesSerialDao = new SalesSerialDao(salesSerialDaoConfig, this);
        soMasterDao = new SoMasterDao(soMasterDaoConfig, this);
        soDetailDao = new SoDetailDao(soDetailDaoConfig, this);
        srMasterDao = new SrMasterDao(srMasterDaoConfig, this);
        srDetailDao = new SrDetailDao(srDetailDaoConfig, this);
        srSerialDao = new SrSerialDao(srSerialDaoConfig, this);

        registerDao(Inbox.class, inboxDao);
        registerDao(Config.class, configDao);
        registerDao(Warehouse.class, warehouseDao);
        registerDao(Salesman.class, salesmanDao);
        registerDao(Item.class, itemDao);
        registerDao(ItemSerial.class, itemSerialDao);
        registerDao(ItemUnit.class, itemUnitDao);
        registerDao(ItemBarcode.class, itemBarcodeDao);
        registerDao(ItemPrice.class, itemPriceDao);
        registerDao(CustomerType.class, customerTypeDao);
        registerDao(Customer.class, customerDao);
        registerDao(CustomerInfo.class, customerInfoDao);
        registerDao(TransferMaster.class, transferMasterDao);
        registerDao(TransferDetail.class, transferDetailDao);
        registerDao(TransferSerial.class, transferSerialDao);
        registerDao(MoveMaster.class, moveMasterDao);
        registerDao(MoveDetail.class, moveDetailDao);
        registerDao(MoveSerial.class, moveSerialDao);
        registerDao(SalesMaster.class, salesMasterDao);
        registerDao(SalesDetail.class, salesDetailDao);
        registerDao(SalesSerial.class, salesSerialDao);
        registerDao(SoMaster.class, soMasterDao);
        registerDao(SoDetail.class, soDetailDao);
        registerDao(SrMaster.class, srMasterDao);
        registerDao(SrDetail.class, srDetailDao);
        registerDao(SrSerial.class, srSerialDao);
    }
    
    public void clear() {
        inboxDaoConfig.getIdentityScope().clear();
        configDaoConfig.getIdentityScope().clear();
        warehouseDaoConfig.getIdentityScope().clear();
        salesmanDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        itemSerialDaoConfig.getIdentityScope().clear();
        itemUnitDaoConfig.getIdentityScope().clear();
        itemBarcodeDaoConfig.getIdentityScope().clear();
        itemPriceDaoConfig.getIdentityScope().clear();
        customerTypeDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        customerInfoDaoConfig.getIdentityScope().clear();
        transferMasterDaoConfig.getIdentityScope().clear();
        transferDetailDaoConfig.getIdentityScope().clear();
        transferSerialDaoConfig.getIdentityScope().clear();
        moveMasterDaoConfig.getIdentityScope().clear();
        moveDetailDaoConfig.getIdentityScope().clear();
        moveSerialDaoConfig.getIdentityScope().clear();
        salesMasterDaoConfig.getIdentityScope().clear();
        salesDetailDaoConfig.getIdentityScope().clear();
        salesSerialDaoConfig.getIdentityScope().clear();
        soMasterDaoConfig.getIdentityScope().clear();
        soDetailDaoConfig.getIdentityScope().clear();
        srMasterDaoConfig.getIdentityScope().clear();
        srDetailDaoConfig.getIdentityScope().clear();
        srSerialDaoConfig.getIdentityScope().clear();
    }

    public InboxDao getInboxDao() {
        return inboxDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

    public WarehouseDao getWarehouseDao() {
        return warehouseDao;
    }

    public SalesmanDao getSalesmanDao() {
        return salesmanDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public ItemSerialDao getItemSerialDao() {
        return itemSerialDao;
    }

    public ItemUnitDao getItemUnitDao() {
        return itemUnitDao;
    }

    public ItemBarcodeDao getItemBarcodeDao() {
        return itemBarcodeDao;
    }

    public ItemPriceDao getItemPriceDao() {
        return itemPriceDao;
    }

    public CustomerTypeDao getCustomerTypeDao() {
        return customerTypeDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public CustomerInfoDao getCustomerInfoDao() {
        return customerInfoDao;
    }

    public TransferMasterDao getTransferMasterDao() {
        return transferMasterDao;
    }

    public TransferDetailDao getTransferDetailDao() {
        return transferDetailDao;
    }

    public TransferSerialDao getTransferSerialDao() {
        return transferSerialDao;
    }

    public MoveMasterDao getMoveMasterDao() {
        return moveMasterDao;
    }

    public MoveDetailDao getMoveDetailDao() {
        return moveDetailDao;
    }

    public MoveSerialDao getMoveSerialDao() {
        return moveSerialDao;
    }

    public SalesMasterDao getSalesMasterDao() {
        return salesMasterDao;
    }

    public SalesDetailDao getSalesDetailDao() {
        return salesDetailDao;
    }

    public SalesSerialDao getSalesSerialDao() {
        return salesSerialDao;
    }

    public SoMasterDao getSoMasterDao() {
        return soMasterDao;
    }

    public SoDetailDao getSoDetailDao() {
        return soDetailDao;
    }

    public SrMasterDao getSrMasterDao() {
        return srMasterDao;
    }

    public SrDetailDao getSrDetailDao() {
        return srDetailDao;
    }

    public SrSerialDao getSrSerialDao() {
        return srSerialDao;
    }

}
