package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INBOX.
 */
public class Inbox {

    private Long ibx_id;
    private Integer ibx_cat;
    private String ibx_sbj;
    private String ibx_from;
    private String ibx_to;
    private java.util.Date ibx_date;
    private String ibx_cnt;
    private Integer ibx_mark;
    private String src_code;
    private String ori_code;
    private String modi_by;
    private Integer mark;
    private java.util.Date modi_date;

    public Inbox() {
    }

    public Inbox(Long ibx_id) {
        this.ibx_id = ibx_id;
    }

    public Inbox(Long ibx_id, Integer ibx_cat, String ibx_sbj, String ibx_from, String ibx_to, java.util.Date ibx_date, String ibx_cnt, Integer ibx_mark, String src_code, String ori_code, String modi_by, Integer mark, java.util.Date modi_date) {
        this.ibx_id = ibx_id;
        this.ibx_cat = ibx_cat;
        this.ibx_sbj = ibx_sbj;
        this.ibx_from = ibx_from;
        this.ibx_to = ibx_to;
        this.ibx_date = ibx_date;
        this.ibx_cnt = ibx_cnt;
        this.ibx_mark = ibx_mark;
        this.src_code = src_code;
        this.ori_code = ori_code;
        this.modi_by = modi_by;
        this.mark = mark;
        this.modi_date = modi_date;
    }

    public Long getIbx_id() {
        return ibx_id;
    }

    public void setIbx_id(Long ibx_id) {
        this.ibx_id = ibx_id;
    }

    public Integer getIbx_cat() {
        return ibx_cat;
    }

    public void setIbx_cat(Integer ibx_cat) {
        this.ibx_cat = ibx_cat;
    }

    public String getIbx_sbj() {
        return ibx_sbj;
    }

    public void setIbx_sbj(String ibx_sbj) {
        this.ibx_sbj = ibx_sbj;
    }

    public String getIbx_from() {
        return ibx_from;
    }

    public void setIbx_from(String ibx_from) {
        this.ibx_from = ibx_from;
    }

    public String getIbx_to() {
        return ibx_to;
    }

    public void setIbx_to(String ibx_to) {
        this.ibx_to = ibx_to;
    }

    public java.util.Date getIbx_date() {
        return ibx_date;
    }

    public void setIbx_date(java.util.Date ibx_date) {
        this.ibx_date = ibx_date;
    }

    public String getIbx_cnt() {
        return ibx_cnt;
    }

    public void setIbx_cnt(String ibx_cnt) {
        this.ibx_cnt = ibx_cnt;
    }

    public Integer getIbx_mark() {
        return ibx_mark;
    }

    public void setIbx_mark(Integer ibx_mark) {
        this.ibx_mark = ibx_mark;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public String getOri_code() {
        return ori_code;
    }

    public void setOri_code(String ori_code) {
        this.ori_code = ori_code;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
