package net.pointbridge.android.sales.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.pointbridge.android.sales.db.ItemPrice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ITEM_PRICE.
*/
public class ItemPriceDao extends AbstractDao<ItemPrice, String> {

    public static final String TABLENAME = "ITEM_PRICE";

    /**
     * Properties of entity ItemPrice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Ipc_id = new Property(0, String.class, "ipc_id", true, "IPC_ID");
        public final static Property Itm_code = new Property(1, String.class, "itm_code", false, "ITM_CODE");
        public final static Property Itm_unit = new Property(2, String.class, "itm_unit", false, "ITM_UNIT");
        public final static Property Ipc_margin = new Property(3, Float.class, "ipc_margin", false, "IPC_MARGIN");
        public final static Property Ipc_vendprice = new Property(4, Float.class, "ipc_vendprice", false, "IPC_VENDPRICE");
        public final static Property Ipc_buyprice = new Property(5, Float.class, "ipc_buyprice", false, "IPC_BUYPRICE");
        public final static Property Ipc_sellprice = new Property(6, Float.class, "ipc_sellprice", false, "IPC_SELLPRICE");
        public final static Property Ipc_level = new Property(7, Integer.class, "ipc_level", false, "IPC_LEVEL");
        public final static Property Curr_code = new Property(8, String.class, "curr_code", false, "CURR_CODE");
        public final static Property Brc_code = new Property(9, String.class, "brc_code", false, "BRC_CODE");
        public final static Property Src_code = new Property(10, String.class, "src_code", false, "SRC_CODE");
        public final static Property Mark = new Property(11, Integer.class, "mark", false, "MARK");
        public final static Property Modi_by = new Property(12, String.class, "modi_by", false, "MODI_BY");
        public final static Property Modi_date = new Property(13, java.util.Date.class, "modi_date", false, "MODI_DATE");
    };

    private Query<ItemPrice> item_Item_price_fk1Query;

    public ItemPriceDao(DaoConfig config) {
        super(config);
    }
    
    public ItemPriceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ITEM_PRICE' (" + //
                "'IPC_ID' TEXT PRIMARY KEY ASC NOT NULL ," + // 0: ipc_id
                "'ITM_CODE' TEXT," + // 1: itm_code
                "'ITM_UNIT' TEXT," + // 2: itm_unit
                "'IPC_MARGIN' REAL," + // 3: ipc_margin
                "'IPC_VENDPRICE' REAL," + // 4: ipc_vendprice
                "'IPC_BUYPRICE' REAL," + // 5: ipc_buyprice
                "'IPC_SELLPRICE' REAL," + // 6: ipc_sellprice
                "'IPC_LEVEL' INTEGER," + // 7: ipc_level
                "'CURR_CODE' TEXT," + // 8: curr_code
                "'BRC_CODE' TEXT," + // 9: brc_code
                "'SRC_CODE' TEXT," + // 10: src_code
                "'MARK' INTEGER," + // 11: mark
                "'MODI_BY' TEXT," + // 12: modi_by
                "'MODI_DATE' INTEGER);"); // 13: modi_date
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_ITEM_PRICE_ITM_CODE ON ITEM_PRICE" +
                " (ITM_CODE);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ITEM_PRICE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ItemPrice entity) {
        stmt.clearBindings();
 
        String ipc_id = entity.getIpc_id();
        if (ipc_id != null) {
            stmt.bindString(1, ipc_id);
        }
 
        String itm_code = entity.getItm_code();
        if (itm_code != null) {
            stmt.bindString(2, itm_code);
        }
 
        String itm_unit = entity.getItm_unit();
        if (itm_unit != null) {
            stmt.bindString(3, itm_unit);
        }
 
        Float ipc_margin = entity.getIpc_margin();
        if (ipc_margin != null) {
            stmt.bindDouble(4, ipc_margin);
        }
 
        Float ipc_vendprice = entity.getIpc_vendprice();
        if (ipc_vendprice != null) {
            stmt.bindDouble(5, ipc_vendprice);
        }
 
        Float ipc_buyprice = entity.getIpc_buyprice();
        if (ipc_buyprice != null) {
            stmt.bindDouble(6, ipc_buyprice);
        }
 
        Float ipc_sellprice = entity.getIpc_sellprice();
        if (ipc_sellprice != null) {
            stmt.bindDouble(7, ipc_sellprice);
        }
 
        Integer ipc_level = entity.getIpc_level();
        if (ipc_level != null) {
            stmt.bindLong(8, ipc_level);
        }
 
        String curr_code = entity.getCurr_code();
        if (curr_code != null) {
            stmt.bindString(9, curr_code);
        }
 
        String brc_code = entity.getBrc_code();
        if (brc_code != null) {
            stmt.bindString(10, brc_code);
        }
 
        String src_code = entity.getSrc_code();
        if (src_code != null) {
            stmt.bindString(11, src_code);
        }
 
        Integer mark = entity.getMark();
        if (mark != null) {
            stmt.bindLong(12, mark);
        }
 
        String modi_by = entity.getModi_by();
        if (modi_by != null) {
            stmt.bindString(13, modi_by);
        }
 
        java.util.Date modi_date = entity.getModi_date();
        if (modi_date != null) {
            stmt.bindLong(14, modi_date.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ItemPrice readEntity(Cursor cursor, int offset) {
        ItemPrice entity = new ItemPrice( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ipc_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // itm_code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // itm_unit
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // ipc_margin
            cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4), // ipc_vendprice
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // ipc_buyprice
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6), // ipc_sellprice
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // ipc_level
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // curr_code
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // brc_code
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // src_code
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // mark
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // modi_by
            cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)) // modi_date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ItemPrice entity, int offset) {
        entity.setIpc_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setItm_code(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setItm_unit(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIpc_margin(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setIpc_vendprice(cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4));
        entity.setIpc_buyprice(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setIpc_sellprice(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
        entity.setIpc_level(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setCurr_code(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBrc_code(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSrc_code(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMark(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setModi_by(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setModi_date(cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(ItemPrice entity, long rowId) {
        return entity.getIpc_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(ItemPrice entity) {
        if(entity != null) {
            return entity.getIpc_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "item_price_fk1" to-many relationship of Item. */
    public List<ItemPrice> _queryItem_Item_price_fk1(String itm_code) {
        synchronized (this) {
            if (item_Item_price_fk1Query == null) {
                QueryBuilder<ItemPrice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Itm_code.eq(null));
                queryBuilder.orderRaw("IPC_ID ASC");
                item_Item_price_fk1Query = queryBuilder.build();
            }
        }
        Query<ItemPrice> query = item_Item_price_fk1Query.forCurrentThread();
        query.setParameter(0, itm_code);
        return query.list();
    }

}
