package net.pointbridge.android.sales.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.pointbridge.android.sales.db.ItemUnit;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ITEM_UNIT.
*/
public class ItemUnitDao extends AbstractDao<ItemUnit, String> {

    public static final String TABLENAME = "ITEM_UNIT";

    /**
     * Properties of entity ItemUnit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Itu_id = new Property(0, String.class, "itu_id", true, "ITU_ID");
        public final static Property Itm_code = new Property(1, String.class, "itm_code", false, "ITM_CODE");
        public final static Property Itm_unit = new Property(2, String.class, "itm_unit", false, "ITM_UNIT");
        public final static Property Itu_qty = new Property(3, Float.class, "itu_qty", false, "ITU_QTY");
        public final static Property Itu_slspoint = new Property(4, Integer.class, "itu_slspoint", false, "ITU_SLSPOINT");
        public final static Property Src_code = new Property(5, String.class, "src_code", false, "SRC_CODE");
        public final static Property Mark = new Property(6, Integer.class, "mark", false, "MARK");
        public final static Property Modi_by = new Property(7, String.class, "modi_by", false, "MODI_BY");
        public final static Property Modi_date = new Property(8, java.util.Date.class, "modi_date", false, "MODI_DATE");
    };

    private Query<ItemUnit> item_Item_unit_fk1Query;

    public ItemUnitDao(DaoConfig config) {
        super(config);
    }
    
    public ItemUnitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ITEM_UNIT' (" + //
                "'ITU_ID' TEXT PRIMARY KEY ASC NOT NULL ," + // 0: itu_id
                "'ITM_CODE' TEXT," + // 1: itm_code
                "'ITM_UNIT' TEXT," + // 2: itm_unit
                "'ITU_QTY' REAL," + // 3: itu_qty
                "'ITU_SLSPOINT' INTEGER," + // 4: itu_slspoint
                "'SRC_CODE' TEXT," + // 5: src_code
                "'MARK' INTEGER," + // 6: mark
                "'MODI_BY' TEXT," + // 7: modi_by
                "'MODI_DATE' INTEGER);"); // 8: modi_date
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_ITEM_UNIT_ITM_CODE ON ITEM_UNIT" +
                " (ITM_CODE);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_ITEM_UNIT_ITM_UNIT ON ITEM_UNIT" +
                " (ITM_UNIT);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ITEM_UNIT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ItemUnit entity) {
        stmt.clearBindings();
 
        String itu_id = entity.getItu_id();
        if (itu_id != null) {
            stmt.bindString(1, itu_id);
        }
 
        String itm_code = entity.getItm_code();
        if (itm_code != null) {
            stmt.bindString(2, itm_code);
        }
 
        String itm_unit = entity.getItm_unit();
        if (itm_unit != null) {
            stmt.bindString(3, itm_unit);
        }
 
        Float itu_qty = entity.getItu_qty();
        if (itu_qty != null) {
            stmt.bindDouble(4, itu_qty);
        }
 
        Integer itu_slspoint = entity.getItu_slspoint();
        if (itu_slspoint != null) {
            stmt.bindLong(5, itu_slspoint);
        }
 
        String src_code = entity.getSrc_code();
        if (src_code != null) {
            stmt.bindString(6, src_code);
        }
 
        Integer mark = entity.getMark();
        if (mark != null) {
            stmt.bindLong(7, mark);
        }
 
        String modi_by = entity.getModi_by();
        if (modi_by != null) {
            stmt.bindString(8, modi_by);
        }
 
        java.util.Date modi_date = entity.getModi_date();
        if (modi_date != null) {
            stmt.bindLong(9, modi_date.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ItemUnit readEntity(Cursor cursor, int offset) {
        ItemUnit entity = new ItemUnit( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // itu_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // itm_code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // itm_unit
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // itu_qty
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // itu_slspoint
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // src_code
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // mark
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // modi_by
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // modi_date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ItemUnit entity, int offset) {
        entity.setItu_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setItm_code(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setItm_unit(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setItu_qty(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setItu_slspoint(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSrc_code(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMark(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setModi_by(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setModi_date(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(ItemUnit entity, long rowId) {
        return entity.getItu_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(ItemUnit entity) {
        if(entity != null) {
            return entity.getItu_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "item_unit_fk1" to-many relationship of Item. */
    public List<ItemUnit> _queryItem_Item_unit_fk1(String itm_code) {
        synchronized (this) {
            if (item_Item_unit_fk1Query == null) {
                QueryBuilder<ItemUnit> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Itm_code.eq(null));
                queryBuilder.orderRaw("ITU_ID ASC");
                item_Item_unit_fk1Query = queryBuilder.build();
            }
        }
        Query<ItemUnit> query = item_Item_unit_fk1Query.forCurrentThread();
        query.setParameter(0, itm_code);
        return query.list();
    }

}
