package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ITEM_SERIAL.
 */
public class ItemSerial {

    private String serial_id;
    private String itm_code;
    private String serial_no;
    private java.util.Date serial_buydate;
    private Integer serial_state;
    private java.util.Date serial_selldate;
    private String wh_code;
    private String cust_code;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public ItemSerial() {
    }

    public ItemSerial(String serial_id) {
        this.serial_id = serial_id;
    }

    public ItemSerial(String serial_id, String itm_code, String serial_no, java.util.Date serial_buydate, Integer serial_state, java.util.Date serial_selldate, String wh_code, String cust_code, String src_code, Integer mark, String modi_by, java.util.Date modi_date) {
        this.serial_id = serial_id;
        this.itm_code = itm_code;
        this.serial_no = serial_no;
        this.serial_buydate = serial_buydate;
        this.serial_state = serial_state;
        this.serial_selldate = serial_selldate;
        this.wh_code = wh_code;
        this.cust_code = cust_code;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getSerial_id() {
        return serial_id;
    }

    public void setSerial_id(String serial_id) {
        this.serial_id = serial_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getSerial_no() {
        return serial_no;
    }

    public void setSerial_no(String serial_no) {
        this.serial_no = serial_no;
    }

    public java.util.Date getSerial_buydate() {
        return serial_buydate;
    }

    public void setSerial_buydate(java.util.Date serial_buydate) {
        this.serial_buydate = serial_buydate;
    }

    public Integer getSerial_state() {
        return serial_state;
    }

    public void setSerial_state(Integer serial_state) {
        this.serial_state = serial_state;
    }

    public java.util.Date getSerial_selldate() {
        return serial_selldate;
    }

    public void setSerial_selldate(java.util.Date serial_selldate) {
        this.serial_selldate = serial_selldate;
    }

    public String getWh_code() {
        return wh_code;
    }

    public void setWh_code(String wh_code) {
        this.wh_code = wh_code;
    }

    public String getCust_code() {
        return cust_code;
    }

    public void setCust_code(String cust_code) {
        this.cust_code = cust_code;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
