package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ITEM_BARCODE.
 */
public class ItemBarcode {

    private String itb_id;
    private String itm_code;
    private String itm_unit;
    private String itb_barcode;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public ItemBarcode() {
    }

    public ItemBarcode(String itb_id) {
        this.itb_id = itb_id;
    }

    public ItemBarcode(String itb_id, String itm_code, String itm_unit, String itb_barcode, String src_code, Integer mark, String modi_by, java.util.Date modi_date) {
        this.itb_id = itb_id;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.itb_barcode = itb_barcode;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getItb_id() {
        return itb_id;
    }

    public void setItb_id(String itb_id) {
        this.itb_id = itb_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public String getItb_barcode() {
        return itb_barcode;
    }

    public void setItb_barcode(String itb_barcode) {
        this.itb_barcode = itb_barcode;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
