package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ITEM_UNIT.
 */
public class ItemUnit {

    private String itu_id;
    private String itm_code;
    private String itm_unit;
    private Float itu_qty;
    private Integer itu_slspoint;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public ItemUnit() {
    }

    public ItemUnit(String itu_id) {
        this.itu_id = itu_id;
    }

    public ItemUnit(String itu_id, String itm_code, String itm_unit, Float itu_qty, Integer itu_slspoint, String src_code, Integer mark, String modi_by, java.util.Date modi_date) {
        this.itu_id = itu_id;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.itu_qty = itu_qty;
        this.itu_slspoint = itu_slspoint;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getItu_id() {
        return itu_id;
    }

    public void setItu_id(String itu_id) {
        this.itu_id = itu_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public Float getItu_qty() {
        return itu_qty;
    }

    public void setItu_qty(Float itu_qty) {
        this.itu_qty = itu_qty;
    }

    public Integer getItu_slspoint() {
        return itu_slspoint;
    }

    public void setItu_slspoint(Integer itu_slspoint) {
        this.itu_slspoint = itu_slspoint;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
