package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOVE_DETAIL.
 */
public class MoveDetail {

    private String md_id;
    private String mm_id;
    private String td_id;
    private String pod_id;
    private String po_no;
    private String tm_no;
    private String itm_code;
    private String itm_unit;
    private Float md_qty;
    private Float md_buyprice;
    private Float md_sellprice;
    private String src_code;
    private String no_seq;
    private Integer proc;
    private Integer astate;
    private Integer locked;
    private Integer posted;
    private Integer mark;
    private Integer modi_by;
    private java.util.Date modi_date;

    public MoveDetail() {
    }

    public MoveDetail(String md_id) {
        this.md_id = md_id;
    }

    public MoveDetail(String md_id, String mm_id, String td_id, String pod_id, String po_no, String tm_no, String itm_code, String itm_unit, Float md_qty, Float md_buyprice, Float md_sellprice, String src_code, String no_seq, Integer proc, Integer astate, Integer locked, Integer posted, Integer mark, Integer modi_by, java.util.Date modi_date) {
        this.md_id = md_id;
        this.mm_id = mm_id;
        this.td_id = td_id;
        this.pod_id = pod_id;
        this.po_no = po_no;
        this.tm_no = tm_no;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.md_qty = md_qty;
        this.md_buyprice = md_buyprice;
        this.md_sellprice = md_sellprice;
        this.src_code = src_code;
        this.no_seq = no_seq;
        this.proc = proc;
        this.astate = astate;
        this.locked = locked;
        this.posted = posted;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getMd_id() {
        return md_id;
    }

    public void setMd_id(String md_id) {
        this.md_id = md_id;
    }

    public String getMm_id() {
        return mm_id;
    }

    public void setMm_id(String mm_id) {
        this.mm_id = mm_id;
    }

    public String getTd_id() {
        return td_id;
    }

    public void setTd_id(String td_id) {
        this.td_id = td_id;
    }

    public String getPod_id() {
        return pod_id;
    }

    public void setPod_id(String pod_id) {
        this.pod_id = pod_id;
    }

    public String getPo_no() {
        return po_no;
    }

    public void setPo_no(String po_no) {
        this.po_no = po_no;
    }

    public String getTm_no() {
        return tm_no;
    }

    public void setTm_no(String tm_no) {
        this.tm_no = tm_no;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public Float getMd_qty() {
        return md_qty;
    }

    public void setMd_qty(Float md_qty) {
        this.md_qty = md_qty;
    }

    public Float getMd_buyprice() {
        return md_buyprice;
    }

    public void setMd_buyprice(Float md_buyprice) {
        this.md_buyprice = md_buyprice;
    }

    public Float getMd_sellprice() {
        return md_sellprice;
    }

    public void setMd_sellprice(Float md_sellprice) {
        this.md_sellprice = md_sellprice;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public String getNo_seq() {
        return no_seq;
    }

    public void setNo_seq(String no_seq) {
        this.no_seq = no_seq;
    }

    public Integer getProc() {
        return proc;
    }

    public void setProc(Integer proc) {
        this.proc = proc;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public Integer getModi_by() {
        return modi_by;
    }

    public void setModi_by(Integer modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
