package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SALES_SERIAL.
 */
public class SalesSerial {

    private String ss_id;
    private String sd_id;
    private String sm_id;
    private String itm_code;
    private String serial_no;
    private String src_code;
    private Integer locked;
    private Integer posted;
    private Integer astate;
    private Integer no_seq;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public SalesSerial() {
    }

    public SalesSerial(String ss_id, String sd_id, String sm_id, String itm_code, String serial_no, String src_code, Integer locked, Integer posted, Integer astate, Integer no_seq, Integer mark, String modi_by, java.util.Date modi_date) {
        this.ss_id = ss_id;
        this.sd_id = sd_id;
        this.sm_id = sm_id;
        this.itm_code = itm_code;
        this.serial_no = serial_no;
        this.src_code = src_code;
        this.locked = locked;
        this.posted = posted;
        this.astate = astate;
        this.no_seq = no_seq;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getSs_id() {
        return ss_id;
    }

    public void setSs_id(String ss_id) {
        this.ss_id = ss_id;
    }

    public String getSd_id() {
        return sd_id;
    }

    public void setSd_id(String sd_id) {
        this.sd_id = sd_id;
    }

    public String getSm_id() {
        return sm_id;
    }

    public void setSm_id(String sm_id) {
        this.sm_id = sm_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getSerial_no() {
        return serial_no;
    }

    public void setSerial_no(String serial_no) {
        this.serial_no = serial_no;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getNo_seq() {
        return no_seq;
    }

    public void setNo_seq(Integer no_seq) {
        this.no_seq = no_seq;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
