package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SALESMAN.
 */
public class Salesman {

    private String slm_code;
    private String slm_name;
    private String slm_address1;
    private String slm_address2;
    private String slm_city;
    private String slm_prov;
    private String slm_country;
    private String slm_email;
    private String slm_phone1;
    private String slm_phone2;
    private String slm_postal;
    private String slm_fax;
    private Integer slm_active;
    private String brc_code;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public Salesman() {
    }

    public Salesman(String slm_code) {
        this.slm_code = slm_code;
    }

    public Salesman(String slm_code, String slm_name, String slm_address1, String slm_address2, String slm_city, String slm_prov, String slm_country, String slm_email, String slm_phone1, String slm_phone2, String slm_postal, String slm_fax, Integer slm_active, String brc_code, String src_code, Integer mark, String modi_by, java.util.Date modi_date) {
        this.slm_code = slm_code;
        this.slm_name = slm_name;
        this.slm_address1 = slm_address1;
        this.slm_address2 = slm_address2;
        this.slm_city = slm_city;
        this.slm_prov = slm_prov;
        this.slm_country = slm_country;
        this.slm_email = slm_email;
        this.slm_phone1 = slm_phone1;
        this.slm_phone2 = slm_phone2;
        this.slm_postal = slm_postal;
        this.slm_fax = slm_fax;
        this.slm_active = slm_active;
        this.brc_code = brc_code;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getSlm_code() {
        return slm_code;
    }

    public void setSlm_code(String slm_code) {
        this.slm_code = slm_code;
    }

    public String getSlm_name() {
        return slm_name;
    }

    public void setSlm_name(String slm_name) {
        this.slm_name = slm_name;
    }

    public String getSlm_address1() {
        return slm_address1;
    }

    public void setSlm_address1(String slm_address1) {
        this.slm_address1 = slm_address1;
    }

    public String getSlm_address2() {
        return slm_address2;
    }

    public void setSlm_address2(String slm_address2) {
        this.slm_address2 = slm_address2;
    }

    public String getSlm_city() {
        return slm_city;
    }

    public void setSlm_city(String slm_city) {
        this.slm_city = slm_city;
    }

    public String getSlm_prov() {
        return slm_prov;
    }

    public void setSlm_prov(String slm_prov) {
        this.slm_prov = slm_prov;
    }

    public String getSlm_country() {
        return slm_country;
    }

    public void setSlm_country(String slm_country) {
        this.slm_country = slm_country;
    }

    public String getSlm_email() {
        return slm_email;
    }

    public void setSlm_email(String slm_email) {
        this.slm_email = slm_email;
    }

    public String getSlm_phone1() {
        return slm_phone1;
    }

    public void setSlm_phone1(String slm_phone1) {
        this.slm_phone1 = slm_phone1;
    }

    public String getSlm_phone2() {
        return slm_phone2;
    }

    public void setSlm_phone2(String slm_phone2) {
        this.slm_phone2 = slm_phone2;
    }

    public String getSlm_postal() {
        return slm_postal;
    }

    public void setSlm_postal(String slm_postal) {
        this.slm_postal = slm_postal;
    }

    public String getSlm_fax() {
        return slm_fax;
    }

    public void setSlm_fax(String slm_fax) {
        this.slm_fax = slm_fax;
    }

    public Integer getSlm_active() {
        return slm_active;
    }

    public void setSlm_active(Integer slm_active) {
        this.slm_active = slm_active;
    }

    public String getBrc_code() {
        return brc_code;
    }

    public void setBrc_code(String brc_code) {
        this.brc_code = brc_code;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
