package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SALES_DETAIL.
 */
public class SalesDetail {

    private String sd_id;
    private String sm_id;
    private String so_no;
    private String sod_id;
    private String itm_code;
    private String itm_unit;
    private Float sd_qty;
    private Float sd_price;
    private Float sd_buyprice;
    private Float sd_disc1;
    private Float sd_disc2;
    private Float sd_discval;
    private Integer sd_inctax;
    private Float sd_taxval;
    private Integer sd_csg;
    private Integer sd_calcpoint;
    private Float sd_othercost;
    private Integer locked;
    private Integer posted;
    private String src_code;
    private Integer astate;
    private String spg;
    private Integer no_seq;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public SalesDetail() {
    }

    public SalesDetail(String sd_id) {
        this.sd_id = sd_id;
    }

    public SalesDetail(String sd_id, String sm_id, String so_no, String sod_id, String itm_code, String itm_unit, Float sd_qty, Float sd_price, Float sd_buyprice, Float sd_disc1, Float sd_disc2, Float sd_discval, Integer sd_inctax, Float sd_taxval, Integer sd_csg, Integer sd_calcpoint, Float sd_othercost, Integer locked, Integer posted, String src_code, Integer astate, String spg, Integer no_seq, Integer mark, String modi_by, java.util.Date modi_date) {
        this.sd_id = sd_id;
        this.sm_id = sm_id;
        this.so_no = so_no;
        this.sod_id = sod_id;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.sd_qty = sd_qty;
        this.sd_price = sd_price;
        this.sd_buyprice = sd_buyprice;
        this.sd_disc1 = sd_disc1;
        this.sd_disc2 = sd_disc2;
        this.sd_discval = sd_discval;
        this.sd_inctax = sd_inctax;
        this.sd_taxval = sd_taxval;
        this.sd_csg = sd_csg;
        this.sd_calcpoint = sd_calcpoint;
        this.sd_othercost = sd_othercost;
        this.locked = locked;
        this.posted = posted;
        this.src_code = src_code;
        this.astate = astate;
        this.spg = spg;
        this.no_seq = no_seq;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getSd_id() {
        return sd_id;
    }

    public void setSd_id(String sd_id) {
        this.sd_id = sd_id;
    }

    public String getSm_id() {
        return sm_id;
    }

    public void setSm_id(String sm_id) {
        this.sm_id = sm_id;
    }

    public String getSo_no() {
        return so_no;
    }

    public void setSo_no(String so_no) {
        this.so_no = so_no;
    }

    public String getSod_id() {
        return sod_id;
    }

    public void setSod_id(String sod_id) {
        this.sod_id = sod_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public Float getSd_qty() {
        return sd_qty;
    }

    public void setSd_qty(Float sd_qty) {
        this.sd_qty = sd_qty;
    }

    public Float getSd_price() {
        return sd_price;
    }

    public void setSd_price(Float sd_price) {
        this.sd_price = sd_price;
    }

    public Float getSd_buyprice() {
        return sd_buyprice;
    }

    public void setSd_buyprice(Float sd_buyprice) {
        this.sd_buyprice = sd_buyprice;
    }

    public Float getSd_disc1() {
        return sd_disc1;
    }

    public void setSd_disc1(Float sd_disc1) {
        this.sd_disc1 = sd_disc1;
    }

    public Float getSd_disc2() {
        return sd_disc2;
    }

    public void setSd_disc2(Float sd_disc2) {
        this.sd_disc2 = sd_disc2;
    }

    public Float getSd_discval() {
        return sd_discval;
    }

    public void setSd_discval(Float sd_discval) {
        this.sd_discval = sd_discval;
    }

    public Integer getSd_inctax() {
        return sd_inctax;
    }

    public void setSd_inctax(Integer sd_inctax) {
        this.sd_inctax = sd_inctax;
    }

    public Float getSd_taxval() {
        return sd_taxval;
    }

    public void setSd_taxval(Float sd_taxval) {
        this.sd_taxval = sd_taxval;
    }

    public Integer getSd_csg() {
        return sd_csg;
    }

    public void setSd_csg(Integer sd_csg) {
        this.sd_csg = sd_csg;
    }

    public Integer getSd_calcpoint() {
        return sd_calcpoint;
    }

    public void setSd_calcpoint(Integer sd_calcpoint) {
        this.sd_calcpoint = sd_calcpoint;
    }

    public Float getSd_othercost() {
        return sd_othercost;
    }

    public void setSd_othercost(Float sd_othercost) {
        this.sd_othercost = sd_othercost;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public String getSpg() {
        return spg;
    }

    public void setSpg(String spg) {
        this.spg = spg;
    }

    public Integer getNo_seq() {
        return no_seq;
    }

    public void setNo_seq(Integer no_seq) {
        this.no_seq = no_seq;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
