package net.pointbridge.android.sales.db;

import java.util.List;
import net.pointbridge.android.sales.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SO_MASTER.
 */
public class SoMaster {

    private String so_id;
    private String so_no;
    private java.util.Date so_date;
    private String cust_code;
    private String slm_code;
    private String curr_code;
    private Float so_totqty;
    private Float so_subtotal;
    private Float so_tottax;
    private Float so_discval;
    private Float so_disc1;
    private Float so_disc2;
    private Float so_disc3;
    private Float so_shipcost;
    private Float so_shipweight;
    private Float so_othercost;
    private Float so_total;
    private Integer so_totalgross;
    private Integer astate;
    private Integer locked;
    private Integer posted;
    private Integer so_inctax;
    private Integer allproc;
    private Integer src_code;
    private Integer mark;
    private Integer modi_by;
    private java.util.Date modi_date;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SoMasterDao myDao;

    private List<SoDetail> so_detail_fk1;

    public SoMaster() {
    }

    public SoMaster(String so_id) {
        this.so_id = so_id;
    }

    public SoMaster(String so_id, String so_no, java.util.Date so_date, String cust_code, String slm_code, String curr_code, Float so_totqty, Float so_subtotal, Float so_tottax, Float so_discval, Float so_disc1, Float so_disc2, Float so_disc3, Float so_shipcost, Float so_shipweight, Float so_othercost, Float so_total, Integer so_totalgross, Integer astate, Integer locked, Integer posted, Integer so_inctax, Integer allproc, Integer src_code, Integer mark, Integer modi_by, java.util.Date modi_date) {
        this.so_id = so_id;
        this.so_no = so_no;
        this.so_date = so_date;
        this.cust_code = cust_code;
        this.slm_code = slm_code;
        this.curr_code = curr_code;
        this.so_totqty = so_totqty;
        this.so_subtotal = so_subtotal;
        this.so_tottax = so_tottax;
        this.so_discval = so_discval;
        this.so_disc1 = so_disc1;
        this.so_disc2 = so_disc2;
        this.so_disc3 = so_disc3;
        this.so_shipcost = so_shipcost;
        this.so_shipweight = so_shipweight;
        this.so_othercost = so_othercost;
        this.so_total = so_total;
        this.so_totalgross = so_totalgross;
        this.astate = astate;
        this.locked = locked;
        this.posted = posted;
        this.so_inctax = so_inctax;
        this.allproc = allproc;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSoMasterDao() : null;
    }

    public String getSo_id() {
        return so_id;
    }

    public void setSo_id(String so_id) {
        this.so_id = so_id;
    }

    public String getSo_no() {
        return so_no;
    }

    public void setSo_no(String so_no) {
        this.so_no = so_no;
    }

    public java.util.Date getSo_date() {
        return so_date;
    }

    public void setSo_date(java.util.Date so_date) {
        this.so_date = so_date;
    }

    public String getCust_code() {
        return cust_code;
    }

    public void setCust_code(String cust_code) {
        this.cust_code = cust_code;
    }

    public String getSlm_code() {
        return slm_code;
    }

    public void setSlm_code(String slm_code) {
        this.slm_code = slm_code;
    }

    public String getCurr_code() {
        return curr_code;
    }

    public void setCurr_code(String curr_code) {
        this.curr_code = curr_code;
    }

    public Float getSo_totqty() {
        return so_totqty;
    }

    public void setSo_totqty(Float so_totqty) {
        this.so_totqty = so_totqty;
    }

    public Float getSo_subtotal() {
        return so_subtotal;
    }

    public void setSo_subtotal(Float so_subtotal) {
        this.so_subtotal = so_subtotal;
    }

    public Float getSo_tottax() {
        return so_tottax;
    }

    public void setSo_tottax(Float so_tottax) {
        this.so_tottax = so_tottax;
    }

    public Float getSo_discval() {
        return so_discval;
    }

    public void setSo_discval(Float so_discval) {
        this.so_discval = so_discval;
    }

    public Float getSo_disc1() {
        return so_disc1;
    }

    public void setSo_disc1(Float so_disc1) {
        this.so_disc1 = so_disc1;
    }

    public Float getSo_disc2() {
        return so_disc2;
    }

    public void setSo_disc2(Float so_disc2) {
        this.so_disc2 = so_disc2;
    }

    public Float getSo_disc3() {
        return so_disc3;
    }

    public void setSo_disc3(Float so_disc3) {
        this.so_disc3 = so_disc3;
    }

    public Float getSo_shipcost() {
        return so_shipcost;
    }

    public void setSo_shipcost(Float so_shipcost) {
        this.so_shipcost = so_shipcost;
    }

    public Float getSo_shipweight() {
        return so_shipweight;
    }

    public void setSo_shipweight(Float so_shipweight) {
        this.so_shipweight = so_shipweight;
    }

    public Float getSo_othercost() {
        return so_othercost;
    }

    public void setSo_othercost(Float so_othercost) {
        this.so_othercost = so_othercost;
    }

    public Float getSo_total() {
        return so_total;
    }

    public void setSo_total(Float so_total) {
        this.so_total = so_total;
    }

    public Integer getSo_totalgross() {
        return so_totalgross;
    }

    public void setSo_totalgross(Integer so_totalgross) {
        this.so_totalgross = so_totalgross;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getSo_inctax() {
        return so_inctax;
    }

    public void setSo_inctax(Integer so_inctax) {
        this.so_inctax = so_inctax;
    }

    public Integer getAllproc() {
        return allproc;
    }

    public void setAllproc(Integer allproc) {
        this.allproc = allproc;
    }

    public Integer getSrc_code() {
        return src_code;
    }

    public void setSrc_code(Integer src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public Integer getModi_by() {
        return modi_by;
    }

    public void setModi_by(Integer modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SoDetail> getSo_detail_fk1() {
        if (so_detail_fk1 == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SoDetailDao targetDao = daoSession.getSoDetailDao();
            List<SoDetail> so_detail_fk1New = targetDao._querySoMaster_So_detail_fk1(so_id);
            synchronized (this) {
                if(so_detail_fk1 == null) {
                    so_detail_fk1 = so_detail_fk1New;
                }
            }
        }
        return so_detail_fk1;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSo_detail_fk1() {
        so_detail_fk1 = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
