package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SR_DETAIL.
 */
public class SrDetail {

    private String srd_id;
    private String sr_id;
    private String sd_id;
    private String itm_code;
    private String itm_unit;
    private Float srd_qty;
    private Float srd_price;
    private Float srd_buyprice;
    private Float srd_disc1;
    private Float srd_disc2;
    private Float srd_discval;
    private Integer srd_inctax;
    private Float srd_taxval;
    private String src_code;
    private Integer no_seq;
    private String proc;
    private Integer astate;
    private Integer locked;
    private Integer posted;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public SrDetail() {
    }

    public SrDetail(String srd_id) {
        this.srd_id = srd_id;
    }

    public SrDetail(String srd_id, String sr_id, String sd_id, String itm_code, String itm_unit, Float srd_qty, Float srd_price, Float srd_buyprice, Float srd_disc1, Float srd_disc2, Float srd_discval, Integer srd_inctax, Float srd_taxval, String src_code, Integer no_seq, String proc, Integer astate, Integer locked, Integer posted, Integer mark, String modi_by, java.util.Date modi_date) {
        this.srd_id = srd_id;
        this.sr_id = sr_id;
        this.sd_id = sd_id;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.srd_qty = srd_qty;
        this.srd_price = srd_price;
        this.srd_buyprice = srd_buyprice;
        this.srd_disc1 = srd_disc1;
        this.srd_disc2 = srd_disc2;
        this.srd_discval = srd_discval;
        this.srd_inctax = srd_inctax;
        this.srd_taxval = srd_taxval;
        this.src_code = src_code;
        this.no_seq = no_seq;
        this.proc = proc;
        this.astate = astate;
        this.locked = locked;
        this.posted = posted;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getSrd_id() {
        return srd_id;
    }

    public void setSrd_id(String srd_id) {
        this.srd_id = srd_id;
    }

    public String getSr_id() {
        return sr_id;
    }

    public void setSr_id(String sr_id) {
        this.sr_id = sr_id;
    }

    public String getSd_id() {
        return sd_id;
    }

    public void setSd_id(String sd_id) {
        this.sd_id = sd_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public Float getSrd_qty() {
        return srd_qty;
    }

    public void setSrd_qty(Float srd_qty) {
        this.srd_qty = srd_qty;
    }

    public Float getSrd_price() {
        return srd_price;
    }

    public void setSrd_price(Float srd_price) {
        this.srd_price = srd_price;
    }

    public Float getSrd_buyprice() {
        return srd_buyprice;
    }

    public void setSrd_buyprice(Float srd_buyprice) {
        this.srd_buyprice = srd_buyprice;
    }

    public Float getSrd_disc1() {
        return srd_disc1;
    }

    public void setSrd_disc1(Float srd_disc1) {
        this.srd_disc1 = srd_disc1;
    }

    public Float getSrd_disc2() {
        return srd_disc2;
    }

    public void setSrd_disc2(Float srd_disc2) {
        this.srd_disc2 = srd_disc2;
    }

    public Float getSrd_discval() {
        return srd_discval;
    }

    public void setSrd_discval(Float srd_discval) {
        this.srd_discval = srd_discval;
    }

    public Integer getSrd_inctax() {
        return srd_inctax;
    }

    public void setSrd_inctax(Integer srd_inctax) {
        this.srd_inctax = srd_inctax;
    }

    public Float getSrd_taxval() {
        return srd_taxval;
    }

    public void setSrd_taxval(Float srd_taxval) {
        this.srd_taxval = srd_taxval;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getNo_seq() {
        return no_seq;
    }

    public void setNo_seq(Integer no_seq) {
        this.no_seq = no_seq;
    }

    public String getProc() {
        return proc;
    }

    public void setProc(String proc) {
        this.proc = proc;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
