package net.pointbridge.android.sales.db;

import java.util.List;
import net.pointbridge.android.sales.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SR_MASTER.
 */
public class SrMaster {

    private String sr_id;
    private String sr_no;
    private java.util.Date sr_date;
    private String sm_no;
    private String cust_code;
    private String wh_code;
    private Integer slm_code;
    private Integer pay_type;
    private Float curr_code;
    private Float curr_val;
    private Float sr_totqty;
    private Float sr_subtotal;
    private Float sr_tottax;
    private Float sr_discval;
    private Float sr_disc1;
    private Float sr_disc2;
    private Float sr_disc3;
    private Float sr_shipcost;
    private Float sr_shipweight;
    private Float sr_othercost;
    private Float sr_total;
    private Float sr_totalgross;
    private Integer sr_proc;
    private Integer sr_inctax;
    private Integer allproc;
    private Integer src_code;
    private Integer astate;
    private Integer locked;
    private Integer posted;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SrMasterDao myDao;

    private List<SrDetail> sr_detail_fk1;
    private List<SrSerial> sr_serial_fk1;

    public SrMaster() {
    }

    public SrMaster(String sr_id) {
        this.sr_id = sr_id;
    }

    public SrMaster(String sr_id, String sr_no, java.util.Date sr_date, String sm_no, String cust_code, String wh_code, Integer slm_code, Integer pay_type, Float curr_code, Float curr_val, Float sr_totqty, Float sr_subtotal, Float sr_tottax, Float sr_discval, Float sr_disc1, Float sr_disc2, Float sr_disc3, Float sr_shipcost, Float sr_shipweight, Float sr_othercost, Float sr_total, Float sr_totalgross, Integer sr_proc, Integer sr_inctax, Integer allproc, Integer src_code, Integer astate, Integer locked, Integer posted, Integer mark, String modi_by, java.util.Date modi_date) {
        this.sr_id = sr_id;
        this.sr_no = sr_no;
        this.sr_date = sr_date;
        this.sm_no = sm_no;
        this.cust_code = cust_code;
        this.wh_code = wh_code;
        this.slm_code = slm_code;
        this.pay_type = pay_type;
        this.curr_code = curr_code;
        this.curr_val = curr_val;
        this.sr_totqty = sr_totqty;
        this.sr_subtotal = sr_subtotal;
        this.sr_tottax = sr_tottax;
        this.sr_discval = sr_discval;
        this.sr_disc1 = sr_disc1;
        this.sr_disc2 = sr_disc2;
        this.sr_disc3 = sr_disc3;
        this.sr_shipcost = sr_shipcost;
        this.sr_shipweight = sr_shipweight;
        this.sr_othercost = sr_othercost;
        this.sr_total = sr_total;
        this.sr_totalgross = sr_totalgross;
        this.sr_proc = sr_proc;
        this.sr_inctax = sr_inctax;
        this.allproc = allproc;
        this.src_code = src_code;
        this.astate = astate;
        this.locked = locked;
        this.posted = posted;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSrMasterDao() : null;
    }

    public String getSr_id() {
        return sr_id;
    }

    public void setSr_id(String sr_id) {
        this.sr_id = sr_id;
    }

    public String getSr_no() {
        return sr_no;
    }

    public void setSr_no(String sr_no) {
        this.sr_no = sr_no;
    }

    public java.util.Date getSr_date() {
        return sr_date;
    }

    public void setSr_date(java.util.Date sr_date) {
        this.sr_date = sr_date;
    }

    public String getSm_no() {
        return sm_no;
    }

    public void setSm_no(String sm_no) {
        this.sm_no = sm_no;
    }

    public String getCust_code() {
        return cust_code;
    }

    public void setCust_code(String cust_code) {
        this.cust_code = cust_code;
    }

    public String getWh_code() {
        return wh_code;
    }

    public void setWh_code(String wh_code) {
        this.wh_code = wh_code;
    }

    public Integer getSlm_code() {
        return slm_code;
    }

    public void setSlm_code(Integer slm_code) {
        this.slm_code = slm_code;
    }

    public Integer getPay_type() {
        return pay_type;
    }

    public void setPay_type(Integer pay_type) {
        this.pay_type = pay_type;
    }

    public Float getCurr_code() {
        return curr_code;
    }

    public void setCurr_code(Float curr_code) {
        this.curr_code = curr_code;
    }

    public Float getCurr_val() {
        return curr_val;
    }

    public void setCurr_val(Float curr_val) {
        this.curr_val = curr_val;
    }

    public Float getSr_totqty() {
        return sr_totqty;
    }

    public void setSr_totqty(Float sr_totqty) {
        this.sr_totqty = sr_totqty;
    }

    public Float getSr_subtotal() {
        return sr_subtotal;
    }

    public void setSr_subtotal(Float sr_subtotal) {
        this.sr_subtotal = sr_subtotal;
    }

    public Float getSr_tottax() {
        return sr_tottax;
    }

    public void setSr_tottax(Float sr_tottax) {
        this.sr_tottax = sr_tottax;
    }

    public Float getSr_discval() {
        return sr_discval;
    }

    public void setSr_discval(Float sr_discval) {
        this.sr_discval = sr_discval;
    }

    public Float getSr_disc1() {
        return sr_disc1;
    }

    public void setSr_disc1(Float sr_disc1) {
        this.sr_disc1 = sr_disc1;
    }

    public Float getSr_disc2() {
        return sr_disc2;
    }

    public void setSr_disc2(Float sr_disc2) {
        this.sr_disc2 = sr_disc2;
    }

    public Float getSr_disc3() {
        return sr_disc3;
    }

    public void setSr_disc3(Float sr_disc3) {
        this.sr_disc3 = sr_disc3;
    }

    public Float getSr_shipcost() {
        return sr_shipcost;
    }

    public void setSr_shipcost(Float sr_shipcost) {
        this.sr_shipcost = sr_shipcost;
    }

    public Float getSr_shipweight() {
        return sr_shipweight;
    }

    public void setSr_shipweight(Float sr_shipweight) {
        this.sr_shipweight = sr_shipweight;
    }

    public Float getSr_othercost() {
        return sr_othercost;
    }

    public void setSr_othercost(Float sr_othercost) {
        this.sr_othercost = sr_othercost;
    }

    public Float getSr_total() {
        return sr_total;
    }

    public void setSr_total(Float sr_total) {
        this.sr_total = sr_total;
    }

    public Float getSr_totalgross() {
        return sr_totalgross;
    }

    public void setSr_totalgross(Float sr_totalgross) {
        this.sr_totalgross = sr_totalgross;
    }

    public Integer getSr_proc() {
        return sr_proc;
    }

    public void setSr_proc(Integer sr_proc) {
        this.sr_proc = sr_proc;
    }

    public Integer getSr_inctax() {
        return sr_inctax;
    }

    public void setSr_inctax(Integer sr_inctax) {
        this.sr_inctax = sr_inctax;
    }

    public Integer getAllproc() {
        return allproc;
    }

    public void setAllproc(Integer allproc) {
        this.allproc = allproc;
    }

    public Integer getSrc_code() {
        return src_code;
    }

    public void setSrc_code(Integer src_code) {
        this.src_code = src_code;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SrDetail> getSr_detail_fk1() {
        if (sr_detail_fk1 == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SrDetailDao targetDao = daoSession.getSrDetailDao();
            List<SrDetail> sr_detail_fk1New = targetDao._querySrMaster_Sr_detail_fk1(sr_id);
            synchronized (this) {
                if(sr_detail_fk1 == null) {
                    sr_detail_fk1 = sr_detail_fk1New;
                }
            }
        }
        return sr_detail_fk1;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSr_detail_fk1() {
        sr_detail_fk1 = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SrSerial> getSr_serial_fk1() {
        if (sr_serial_fk1 == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SrSerialDao targetDao = daoSession.getSrSerialDao();
            List<SrSerial> sr_serial_fk1New = targetDao._querySrMaster_Sr_serial_fk1(sr_id);
            synchronized (this) {
                if(sr_serial_fk1 == null) {
                    sr_serial_fk1 = sr_serial_fk1New;
                }
            }
        }
        return sr_serial_fk1;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSr_serial_fk1() {
        sr_serial_fk1 = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
