package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRANSFER_DETAIL.
 */
public class TransferDetail {

    private String td_id;
    private String tm_id;
    private String itm_code;
    private String itm_unit;
    private Float td_qty;
    private Float td_buyprice;
    private Float td_sellprice;
    private String src_code;
    private Integer astate;
    private Integer locked;
    private Integer posted;
    private Integer mark;
    private Integer no_seq;
    private String modi_by;
    private java.util.Date modi_date;

    public TransferDetail() {
    }

    public TransferDetail(String td_id) {
        this.td_id = td_id;
    }

    public TransferDetail(String td_id, String tm_id, String itm_code, String itm_unit, Float td_qty, Float td_buyprice, Float td_sellprice, String src_code, Integer astate, Integer locked, Integer posted, Integer mark, Integer no_seq, String modi_by, java.util.Date modi_date) {
        this.td_id = td_id;
        this.tm_id = tm_id;
        this.itm_code = itm_code;
        this.itm_unit = itm_unit;
        this.td_qty = td_qty;
        this.td_buyprice = td_buyprice;
        this.td_sellprice = td_sellprice;
        this.src_code = src_code;
        this.astate = astate;
        this.locked = locked;
        this.posted = posted;
        this.mark = mark;
        this.no_seq = no_seq;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getTd_id() {
        return td_id;
    }

    public void setTd_id(String td_id) {
        this.td_id = td_id;
    }

    public String getTm_id() {
        return tm_id;
    }

    public void setTm_id(String tm_id) {
        this.tm_id = tm_id;
    }

    public String getItm_code() {
        return itm_code;
    }

    public void setItm_code(String itm_code) {
        this.itm_code = itm_code;
    }

    public String getItm_unit() {
        return itm_unit;
    }

    public void setItm_unit(String itm_unit) {
        this.itm_unit = itm_unit;
    }

    public Float getTd_qty() {
        return td_qty;
    }

    public void setTd_qty(Float td_qty) {
        this.td_qty = td_qty;
    }

    public Float getTd_buyprice() {
        return td_buyprice;
    }

    public void setTd_buyprice(Float td_buyprice) {
        this.td_buyprice = td_buyprice;
    }

    public Float getTd_sellprice() {
        return td_sellprice;
    }

    public void setTd_sellprice(Float td_sellprice) {
        this.td_sellprice = td_sellprice;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getAstate() {
        return astate;
    }

    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getPosted() {
        return posted;
    }

    public void setPosted(Integer posted) {
        this.posted = posted;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public Integer getNo_seq() {
        return no_seq;
    }

    public void setNo_seq(Integer no_seq) {
        this.no_seq = no_seq;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
