package net.pointbridge.android.sales.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.pointbridge.android.sales.db.TransferDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TRANSFER_DETAIL.
*/
public class TransferDetailDao extends AbstractDao<TransferDetail, String> {

    public static final String TABLENAME = "TRANSFER_DETAIL";

    /**
     * Properties of entity TransferDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Td_id = new Property(0, String.class, "td_id", true, "TD_ID");
        public final static Property Tm_id = new Property(1, String.class, "tm_id", false, "TM_ID");
        public final static Property Itm_code = new Property(2, String.class, "itm_code", false, "ITM_CODE");
        public final static Property Itm_unit = new Property(3, String.class, "itm_unit", false, "ITM_UNIT");
        public final static Property Td_qty = new Property(4, Float.class, "td_qty", false, "TD_QTY");
        public final static Property Td_buyprice = new Property(5, Float.class, "td_buyprice", false, "TD_BUYPRICE");
        public final static Property Td_sellprice = new Property(6, Float.class, "td_sellprice", false, "TD_SELLPRICE");
        public final static Property Src_code = new Property(7, String.class, "src_code", false, "SRC_CODE");
        public final static Property Astate = new Property(8, Integer.class, "astate", false, "ASTATE");
        public final static Property Locked = new Property(9, Integer.class, "locked", false, "LOCKED");
        public final static Property Posted = new Property(10, Integer.class, "posted", false, "POSTED");
        public final static Property Mark = new Property(11, Integer.class, "mark", false, "MARK");
        public final static Property No_seq = new Property(12, Integer.class, "no_seq", false, "NO_SEQ");
        public final static Property Modi_by = new Property(13, String.class, "modi_by", false, "MODI_BY");
        public final static Property Modi_date = new Property(14, java.util.Date.class, "modi_date", false, "MODI_DATE");
    };

    private Query<TransferDetail> transferMaster_Tr_detail_fk1Query;

    public TransferDetailDao(DaoConfig config) {
        super(config);
    }
    
    public TransferDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TRANSFER_DETAIL' (" + //
                "'TD_ID' TEXT PRIMARY KEY ASC NOT NULL ," + // 0: td_id
                "'TM_ID' TEXT," + // 1: tm_id
                "'ITM_CODE' TEXT," + // 2: itm_code
                "'ITM_UNIT' TEXT," + // 3: itm_unit
                "'TD_QTY' REAL," + // 4: td_qty
                "'TD_BUYPRICE' REAL," + // 5: td_buyprice
                "'TD_SELLPRICE' REAL," + // 6: td_sellprice
                "'SRC_CODE' TEXT," + // 7: src_code
                "'ASTATE' INTEGER," + // 8: astate
                "'LOCKED' INTEGER," + // 9: locked
                "'POSTED' INTEGER," + // 10: posted
                "'MARK' INTEGER," + // 11: mark
                "'NO_SEQ' INTEGER," + // 12: no_seq
                "'MODI_BY' TEXT," + // 13: modi_by
                "'MODI_DATE' INTEGER);"); // 14: modi_date
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TRANSFER_DETAIL_TM_ID ON TRANSFER_DETAIL" +
                " (TM_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TRANSFER_DETAIL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TransferDetail entity) {
        stmt.clearBindings();
 
        String td_id = entity.getTd_id();
        if (td_id != null) {
            stmt.bindString(1, td_id);
        }
 
        String tm_id = entity.getTm_id();
        if (tm_id != null) {
            stmt.bindString(2, tm_id);
        }
 
        String itm_code = entity.getItm_code();
        if (itm_code != null) {
            stmt.bindString(3, itm_code);
        }
 
        String itm_unit = entity.getItm_unit();
        if (itm_unit != null) {
            stmt.bindString(4, itm_unit);
        }
 
        Float td_qty = entity.getTd_qty();
        if (td_qty != null) {
            stmt.bindDouble(5, td_qty);
        }
 
        Float td_buyprice = entity.getTd_buyprice();
        if (td_buyprice != null) {
            stmt.bindDouble(6, td_buyprice);
        }
 
        Float td_sellprice = entity.getTd_sellprice();
        if (td_sellprice != null) {
            stmt.bindDouble(7, td_sellprice);
        }
 
        String src_code = entity.getSrc_code();
        if (src_code != null) {
            stmt.bindString(8, src_code);
        }
 
        Integer astate = entity.getAstate();
        if (astate != null) {
            stmt.bindLong(9, astate);
        }
 
        Integer locked = entity.getLocked();
        if (locked != null) {
            stmt.bindLong(10, locked);
        }
 
        Integer posted = entity.getPosted();
        if (posted != null) {
            stmt.bindLong(11, posted);
        }
 
        Integer mark = entity.getMark();
        if (mark != null) {
            stmt.bindLong(12, mark);
        }
 
        Integer no_seq = entity.getNo_seq();
        if (no_seq != null) {
            stmt.bindLong(13, no_seq);
        }
 
        String modi_by = entity.getModi_by();
        if (modi_by != null) {
            stmt.bindString(14, modi_by);
        }
 
        java.util.Date modi_date = entity.getModi_date();
        if (modi_date != null) {
            stmt.bindLong(15, modi_date.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TransferDetail readEntity(Cursor cursor, int offset) {
        TransferDetail entity = new TransferDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // td_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tm_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // itm_code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // itm_unit
            cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4), // td_qty
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // td_buyprice
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6), // td_sellprice
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // src_code
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // astate
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // locked
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // posted
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // mark
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // no_seq
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // modi_by
            cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)) // modi_date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TransferDetail entity, int offset) {
        entity.setTd_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTm_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setItm_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setItm_unit(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTd_qty(cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4));
        entity.setTd_buyprice(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setTd_sellprice(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
        entity.setSrc_code(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAstate(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setLocked(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setPosted(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setMark(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setNo_seq(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setModi_by(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setModi_date(cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(TransferDetail entity, long rowId) {
        return entity.getTd_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(TransferDetail entity) {
        if(entity != null) {
            return entity.getTd_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tr_detail_fk1" to-many relationship of TransferMaster. */
    public List<TransferDetail> _queryTransferMaster_Tr_detail_fk1(String tm_id) {
        synchronized (this) {
            if (transferMaster_Tr_detail_fk1Query == null) {
                QueryBuilder<TransferDetail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Tm_id.eq(null));
                queryBuilder.orderRaw("TD_ID ASC");
                transferMaster_Tr_detail_fk1Query = queryBuilder.build();
            }
        }
        Query<TransferDetail> query = transferMaster_Tr_detail_fk1Query.forCurrentThread();
        query.setParameter(0, tm_id);
        return query.list();
    }

}
