package net.pointbridge.android.sales.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WAREHOUSE.
 */
public class Warehouse {

    private String wh_code;
    private String wh_name;
    private Integer wh_istransit;
    private Integer wh_active;
    private String brc_code;
    private String src_code;
    private Integer mark;
    private String modi_by;
    private java.util.Date modi_date;

    public Warehouse() {
    }

    public Warehouse(String wh_code) {
        this.wh_code = wh_code;
    }

    public Warehouse(String wh_code, String wh_name, Integer wh_istransit, Integer wh_active, String brc_code, String src_code, Integer mark, String modi_by, java.util.Date modi_date) {
        this.wh_code = wh_code;
        this.wh_name = wh_name;
        this.wh_istransit = wh_istransit;
        this.wh_active = wh_active;
        this.brc_code = brc_code;
        this.src_code = src_code;
        this.mark = mark;
        this.modi_by = modi_by;
        this.modi_date = modi_date;
    }

    public String getWh_code() {
        return wh_code;
    }

    public void setWh_code(String wh_code) {
        this.wh_code = wh_code;
    }

    public String getWh_name() {
        return wh_name;
    }

    public void setWh_name(String wh_name) {
        this.wh_name = wh_name;
    }

    public Integer getWh_istransit() {
        return wh_istransit;
    }

    public void setWh_istransit(Integer wh_istransit) {
        this.wh_istransit = wh_istransit;
    }

    public Integer getWh_active() {
        return wh_active;
    }

    public void setWh_active(Integer wh_active) {
        this.wh_active = wh_active;
    }

    public String getBrc_code() {
        return brc_code;
    }

    public void setBrc_code(String brc_code) {
        this.brc_code = brc_code;
    }

    public String getSrc_code() {
        return src_code;
    }

    public void setSrc_code(String src_code) {
        this.src_code = src_code;
    }

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public String getModi_by() {
        return modi_by;
    }

    public void setModi_by(String modi_by) {
        this.modi_by = modi_by;
    }

    public java.util.Date getModi_date() {
        return modi_date;
    }

    public void setModi_date(java.util.Date modi_date) {
        this.modi_date = modi_date;
    }

}
